name: Manual Input
on:
  workflow_dispatch:
    inputs:
      names:
        description: target names(comma separated)
        required: true
        default: all
        
jobs:
  hoge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: with parameter
        env:
          INPUT_NAMES: ${{ inputs.names }}
        run: |
          echo ${INPUT_NAMES} | tr , '\n'
          
